In [4]:
import numpy as np
import sys
import os
from os.path import join as pjoin


# root_rot_velocity (B, seq_len, 1)
# root_linear_velocity (B, seq_len, 2)
# root_y (B, seq_len, 1)
# ric_data (B, seq_len, (joint_num - 1)*3)
# rot_data (B, seq_len, (joint_num - 1)*6)
# local_velocity (B, seq_len, joint_num*3)
# foot contact (B, seq_len, 4)
def mean_variance(data_dir, save_dir, joints_num): #相对表示的均值和方差
    file_list = os.listdir(data_dir)
    data_list = []

    for file in file_list:
        data = np.load(pjoin(data_dir, file))
        if np.isnan(data).any():
            print(file)
            continue
        data_list.append(data)

    data = np.concatenate(data_list, axis=0)
    print(data.shape)
    Mean = data.mean(axis=0)
    Std = data.std(axis=0)
    Std[0:1] = Std[0:1].mean() / 1.0
    Std[1:3] = Std[1:3].mean() / 1.0
    Std[3:4] = Std[3:4].mean() / 1.0
    Std[4: 4+(joints_num - 1) * 3] = Std[4: 4+(joints_num - 1) * 3].mean() / 1.0
    Std[4+(joints_num - 1) * 3: 4+(joints_num - 1) * 9] = Std[4+(joints_num - 1) * 3: 4+(joints_num - 1) * 9].mean() / 1.0
    Std[4+(joints_num - 1) * 9: 4+(joints_num - 1) * 9 + joints_num*3] = Std[4+(joints_num - 1) * 9: 4+(joints_num - 1) * 9 + joints_num*3].mean() / 1.0
    Std[4 + (joints_num - 1) * 9 + joints_num * 3: ] = Std[4 + (joints_num - 1) * 9 + joints_num * 3: ].mean() / 1.0

    assert 8 + (joints_num - 1) * 9 + joints_num * 3 == Std.shape[-1]

    np.save(pjoin(save_dir, 'Mean.npy'), Mean)
    np.save(pjoin(save_dir, 'Std.npy'), Std)

    return Mean, Std

In [3]:
def mean_variance_raw(data_dir, save_dir): #全局位置的均值和方差
    file_list = os.listdir(data_dir)
    data_list = []

    for file in file_list:
        data = np.load(pjoin(data_dir, file))
        if np.isnan(data).any():
            print(file)
            continue
        data_list.append(data)

    data = np.concatenate(data_list, axis=0)
    print(data.shape)
    Mean = data.mean(axis=0)
    Std = data.std(axis=0)

    np.save(pjoin(save_dir, 'Mean_raw.npy'), Mean)
    np.save(pjoin(save_dir, 'Std_raw.npy'), Std)

    return Mean, Std

In [7]:
if __name__ == '__main__':
    data_dir = '/sata/public/yyqi/Dataset/OCEAN/new_joints/'
    save_dir = '/sata/public/yyqi/Dataset/OCEAN/'
    # mean, std = mean_variance(data_dir, save_dir, 22)
    mean, std = mean_variance_raw(data_dir,save_dir)

    data_dir_vec = '/sata/public/yyqi/Dataset/OCEAN/new_joint_vecs/'
    save_dir_vec = '/sata/public/yyqi/Dataset/OCEAN/'
    mean_vec, std_vec = mean_variance(data_dir_vec, save_dir_vec, 22)


    print(mean)
    print(std)

(2684682, 22, 3)
(2684682, 263)
[[ 1.85889832e-03  8.21729898e-01  2.06373796e-01]
 [ 4.74626347e-02  7.22078741e-01  1.98859230e-01]
 [-4.63037640e-02  7.18142331e-01  2.03606859e-01]
 [ 2.86853348e-04  9.23918009e-01  1.75564572e-01]
 [ 8.60795006e-02  4.19837147e-01  2.74427533e-01]
 [-9.97611955e-02  4.21971291e-01  2.79656827e-01]
 [ 6.45508850e-03  1.01511693e+00  1.77516043e-01]
 [ 7.40409419e-02  6.00970685e-02  2.34032750e-01]
 [-1.03523687e-01  7.17998743e-02  2.37058401e-01]
 [ 2.41553667e-03  1.06512034e+00  2.00170517e-01]
 [ 8.49210545e-02  2.17483751e-02  3.14506710e-01]
 [-1.12192824e-01  3.08326669e-02  3.12687546e-01]
 [-4.95923497e-03  1.23284161e+00  2.14314133e-01]
 [ 4.31127734e-02  1.17654526e+00  2.12073818e-01]
 [-4.11896408e-02  1.17443359e+00  2.09594965e-01]
 [ 5.22569194e-03  1.37797177e+00  2.74733633e-01]
 [ 1.12396039e-01  1.19715631e+00  2.14579001e-01]
 [-1.13312311e-01  1.19626427e+00  2.19880491e-01]
 [ 1.77621081e-01  9.78347600e-01  2.33150125e-01]

### Check if your data is correct. If it's aligned with the given reference, then it is right

In [3]:
abs(mean-reference1).sum()

NameError: name 'reference1' is not defined

In [ ]:
abs(std-reference2).sum()

0.0